#ifndef GreenSolver_H
#define GreenSolver_H

#include <mpi.h>
#include "../cDBCSR.H"
#include "../cDBCSR_tools.H"
#include "../conversion.H"
#include "../array_tools.H"

using namespace std;

#include <math.h>
#include <iostream>
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <limits>

//#include "GSheaders/ElTransport.H"
//#include "GSheaders/PhTransport.H"
#include "../Types.H"
#include "../Utilities.H"
#include "../InputParameter.H"
#include "../MPI_Timing.H"
#include "../ScaLapack.H"
#include "../Blas.H"
#include "../CSR.H"

//#include "LinearSolver.H"
//#include "SuperLU.H"
//#include "Umfpack.H"
//#include "MUMPS.H"
//#include "Pardiso.H"

#endif
