#!/bin/bash
if [ $# -ne 4 ]; 
    then echo "run with input_file output_file number_of_cells size_of_cell"
elif [ -f $2 ]; then
   echo "OUTPUT FILE EXISTS ALREADY"
else
echo "`head -n 1 $1`*$3" | bc > $2
echo >> $2
for (( i=0; i<$3; i++ ))
do
   tail -n +3 $1 | awk '{print $1,$2,$3,$4+"'"$4"'"*"'"$i"'"}' >> $2
done
fi
echo "$3*$4" | bc
