#!/bin/bash

rm ./fermilevels
for p in `seq -0.8 +0.2 0.6`
do
cd gate_${p}
grep FERMI cnt8.log | awk '{print $1}' | tail -1 >> ../fermilevels
awk '{print $2}' CurrentFromTransmission > ./CurrentFromTransmissionCut
awk '{print $2}' CurrentFromBandstructure > ./CurrentFromBandstructureCut
cp Transmission ../Transmission_${p}
cp EnergiesWRTk2 ../EnergiesWRTk_GATE_${p}
cp EnergiesWRTk0 ../EnergiesWRTk_SOURCE_${p}
mv *.cube ../
grep "Total charge density on r-space grids" cnt8.out | awk '{print $7}' > ../charge_${p}
../mullikenextractor cnt8.out > mulliken_${p}
echo ${p}
cd ..
done
for p in `seq -0.8 +0.2 0.6`; do echo ./gate_${p}/mulliken_${p}; done | xargs paste > mulliken
for p in `seq -0.8 +0.2 0.6`; do echo ./gate_${p}/CurrentFromTransmissionCut; done | xargs paste > CurrentFromTransmission
for p in `seq -0.8 +0.2 0.6`; do echo ./gate_${p}/CurrentFromBandstructureCut; done | xargs paste > CurrentFromBandstructure

